name: Train and Save Model to S3

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:

  setup:
    name: Setup & Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: pip install -r requirements/requirements.txt

      - name: Upload Dependencies
        uses: actions/upload-artifact@v4
        with:
          name: python-dependencies
          path: ~/.cache/pip

  train:
    name: Train Model
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Dependencies
        uses: actions/download-artifact@v4
        with:
          name: python-dependencies
          path: ~/.cache/pip

      - name: Install Dependencies (Ensure Installation)
        run: pip install -r requirements/requirements.txt

      - name: Train Model
        run: |
          python housing_prediction/train_pipeline.py
          python housing_prediction/predict.py

      - name: Save training metrics to summary
        run: |
           echo "### ✅ Model Training Complete" >> $GITHUB_STEP_SUMMARY
           cat metrics.txt >> $GITHUB_STEP_SUMMARY

      - name: Save Trained Model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: housing_prediction/trained_models/

  
  Save_Model:
    name: Save Model to S3
    needs: train
    runs-on: ubuntu-latest
    # environment: PROD
    permissions:
      id-token: write # This is crucial for OIDC
      contents: read # To checkout the code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install AWS cli
        run: |
          python -m pip install --upgrade pip
          pip install awscli


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::008971663545:role/s3-iam-role
          aws-region: us-east-1
    
      - name: Download Trained Model
        uses: actions/download-artifact@v4
        with:
            name: trained-model
            path: housing_prediction/trained_models/

      - name: Upload model to S3
        run: aws s3 cp housing_prediction/trained_models/ s3://model-artifactory-kaushik/housing_predictions/ --recursive
        

  build_python_package:
    name: Build Python Package
    needs: Save_Model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Dependencies
        uses: actions/download-artifact@v4
        with:
          name: python-dependencies
          path: ~/.cache/pip

      - name: Install Dependencies
        run: pip install -r requirements/requirements.txt

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Build Package (.whl)
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload Model Package as Artifact 
        uses: actions/upload-artifact@v4
        with:
          name: model-package
          path: dist/*.whl

      - name: Create GitHub Release and Upload Wheel
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: dist/*.whl
          token: ${{ secrets.GITHUB_TOKEN }}

      
